import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";
import { Post } from "@prisma/client";
import { useState } from "react";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const [input, setInput] = useState<string>("");

  const { user } = useUser();
  if (!user) return null;
  const ctx = api.useContext();
  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      ctx.posts.getAll.invalidate();
    },
  });

  return (
    <div className="flex w-full gap-4">
      <Image
        className="flex h-12 w-12 rounded-full"
        src={user.profileImageUrl}
        alt={`@${user.username}'s profile image`}
        width={48}
        height={48}
      />
      <input
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
        value={input}
        disabled={isPosting}
        onChange={(e) => setInput(e.target.value)}
      />
      <button onClick={() => mutate({ content: input })}>Post</button>
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  console.log(author, "author");
  return (
    <div className="flex gap-3 border-b border-slate-400 p-8">
      <Image
        alt="author image"
        src={author.profileImageUrl}
        className="flex h-12 w-12 rounded-full"
        width={48}
        height={48}
      />
      <div className="flex flex-col">
        <div className="flex gap-2 text-slate-300">
          <span>@{author.username}</span>{" "}
          <span className="font-thin">
            {` .  ${dayjs(post.createdAt).fromNow()}`}{" "}
          </span>
        </div>
        <span>{post.content} </span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postLoading } = api.posts.getAll.useQuery();
  const dataEntry = data!;
  console.log(postLoading, "postLoading");
  if (postLoading) return <LoadingPage />;

  if (!dataEntry) return <div>something went wrong</div>;
  console.log(data, "data");

  return (
    <div className="flex flex-col justify-center">
      {dataEntry?.map((fullPost) => (
        <PostView {...fullPost} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();
  const { user, isLoaded: userLoaded, isSignedIn } = useUser();
  if (!userLoaded) return <div />;
  // if (!postLoaded && !userLoaded) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4 ">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!isSignedIn && <SignOutButton />}
            {!!isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
